### ISSUE TITLE
Maximum call stack size exceeded at BinarySearchTree.compareThings

### ISSUE THREAD

**Issue by vladmandic** [jrop/nedb-promise#14]
this happens when trying to delete some specific records  
record itself is perfectly valid and can be read without issues, just cannot be deleted  
note this happens to only small number of records in database, but its fully reproducible with specific record in question  

```js
const data = await db.findOne({ image: param });
if (data) await db.remove({ image: data.image }, { multi: false });
```

causes immediate crash with trace as follows:

```log
/home/vlado/dev/pigallery/node_modules/.pnpm/@seald-io+nedb@2.0.3/node_modules/@seald-io/nedb/lib/model.js:175
const compareThings = (a, b, _compareStrings) => {
                      ^

RangeError: Maximum call stack size exceeded
    at BinarySearchTree.compareThings [as compareKeys] (/home/vlado/dev/pigallery/node_modules/.pnpm/@seald-io+nedb@2.0.3/node_modules/@seald-io/nedb/lib/model.js:175:23)
    at BinarySearchTree.delete (/home/vlado/dev/pigallery/node_modules/.pnpm/@seald-io+binary-search-tree@1.0.2/node_modules/@seald-io/binary-search-tree/lib/bst.js:348:14)
    at BinarySearchTree.delete (/home/vlado/dev/pigallery/node_modules/.pnpm/@seald-io+binary-search-tree@1.0.2/node_modules/@seald-io/binary-search-tree/lib/bst.js:354:40)
    at BinarySearchTree.delete (/home/vlado/dev/pigallery/node_modules/.pnpm/@seald-io+binary-search-tree@1.0.2/node_modules/@seald-io/binary-search-tree/lib/bst.js:354:40)
    at BinarySearchTree.delete (/home/vlado/dev/pigallery/node_modules/.pnpm/@seald-io+binary-search-tree@1.0.2/node_modules/@seald-io/binary-search-tree/lib/bst.js:354:40)
```

workaround is to run `node --stack-size=8192` and then there are no issues,  
but this really should not be necessary for a DB of this size  
(database itself is ~500MB with 10K records in a table)  

package versions are `nedb-promises` 5.0.0 with included version of `@seald-io/nedb` 2.0.3  

environment is nodejs 16.0.0 on ubuntu 21.04

**Comment by jrop** [comment]
@vladmandic If I am not mistaken, the problem looks to reside in the @seald-io/* modules, not this wrapper.  This wrapper is pretty simple in that it just delegates to the underlying engine.

**Comment by vladmandic** [comment]
true (and i'll open an issue there as well), but i don't recall having similar issues with `nedb-promises` before it switched from orignal `nedb` to `@seald-io/nedb` port.

**Comment by vladmandic** [comment]
@jrop

This is now fixed in the underlying library (see linked issue for details), I suggest updating dependencies and releasing new version of `nedb-promise`.

**Comment by jrop** [comment]
@vladmandic would you be willing to create a PR?  I'm a bit busy today

**Comment by jrop** [comment]
@vladmandic Actually, aren't you passing your own engine to this lib?  Shouldn't you update the lib and then require/pass the updated version to this wrapper lib?

**Comment by eliot-akira** [comment]
@vladmandic Perhaps you're using [`nedb-promises`](https://github.com/bajankristof/nedb-promises), with an "s" at the end. It uses `@seald-io/nedb`, currently a version behind.

**Comment by vladmandic** [comment]
> @vladmandic Perhaps you're using nedb-promises, with an "s" at the end. It uses @seald-io/nedb, currently a version behind.

you're right, my bad. closing the issue..
